### ISSUE TITLE
Over-the-Air testing unsuccessful (so far)

### ISSUE THREAD

**Issue by K4KDR** [esa/gr-opssat#1]
Thank you for the outstanding decoder flowgraphs and documentation!  Best wishes for a 100% successful mission.

Using your test file, I can use a 9k6 capable radio to simulate the satellite for in-house testing.  On my linux system, I can use GQRX & Direwolf to show that I am receiving and decoding the 9k6 payload properly "live" over-the-air.

Unfortunately, I have not been able to see the same success using the GNU Radio flowgraphs.  It may be helpful to better understand some of the settings in the flowgraph to find my shortcoming.

Could you please explain what the "samp_rate_down" variable (default value = 57600) represents?

Understanding the definition of that variable might help me find out why I am not able to see the same successful decode in the flowgraphs that I do with Direwolf from the same SDR receiver.

Thank you very much!

-Scott,  K4KDR

**Comment by TomMladenov** [comment]
Hello Scott,

Live on-air tests were successful at ESOC, we used the UHF transceiver of the engineering model of the satellite connected to an antenna for the transmission and received this using an RTL-SDR and configured the flowgraphs per instructions in the README.md for live reception.

The "samp_rated_down" is the decimated samplerate after raw acquisition and should not really be changed. Which SDR and what settings are you using for reception? Maybe check if the frequency correction is on point. 

Not sure which radio you are using to transmit but if you have a more advanced SDR, try just transmitting the IQ file to emulate the downlink.

-Tom

**Comment by K4KDR** [comment]
Thank you so much for the reply, Tom!

The SDR is an Airspy R2 using an external 10m GPSDO reference for frequency stabilization.  Of course any test is meaningless unless you have a reference, so using GQRX & Direwolf with the Airspy allowed me to confirm that my test signal was valid.

Screen shot:

[https://www.qsl.net/k/k4kdr//images/ops-sat-gqrx-test.png](url)

I do not have a method to transmit the original raw test file, but rather am using 15k wide audio recorded from playback of the original test file.  Since I am able to test the result over-the-air to GQRX/Direwolf, I felt that I had a valid test setup.

Thanks so for clarifying the "samp_rate_down" variable!  I will leave that value set to 57600 and work on other aspects of the flowgraph.  

Also, I see that there is now an OPS-Sat decoder in gr-satellites which allows me to feed UDP audio from GQRX (negating the need to incorporate an SDR or doppler correction into the decoder flowgraph), so that option may be easier for me to use.

Thanks again for the help and great project!

-Scott

**Comment by TomMladenov** [comment]
Hi Scott,

A while back I did a test with a LimeSDR Mini and transmitted the IQ file, and used an RTL-SDR to receive and demod. All working fine. Maybe somehow in your transmitted signal some layer aspects are slightly different. Anyhow great to hear all the positive comments from the community.

Good luck in the hunt!
-Tom
