### ISSUE TITLE
Can not set initial freq for doppler correction in gpredict ...

### ISSUE THREAD

**Issue by Yume303** [esa/gr-opssat#2]
Maybe I miss something, but can not set 437.2 initial frequency in gpredict for live tracking. It defaults to 145.890 as the default for gpredict. It works for gqrx, etc. but not for the receiving flowgraph. As seen on the following screenshoot:
![Screenshot_2019-12-15_11-44-55](https://user-images.githubusercontent.com/37635139/70860997-9fe59e80-1f28-11ea-97f9-82455b922a37.png)
I assume I can not see any gr-gpredict doppler block in the flowgraph and the satellite atm (by nature) is missing from the transmitters.json file.

**Comment by mathzol** [comment]
You have to set the downlink frequency manually, than click on Track. For Engage you have to run first UHF RX flow in GnuRadio, it will be create a "server" for listening and GPredict Radio control will connect to it when click on Engage. For debug you can set debug mode in GPredict block on.

**Comment by Yume303** [comment]
Okay, adjusted it manually, now it works well.
Thanks.
