### ISSUE TITLE
Hardcoded developer path

### ISSUE THREAD

**Issue by probonopd** [esa/gr-opssat#3]
When trying to run `os_uhf_rx.grc` in GNU Radio Companion, I get an error involving `/home/osops/tom/dev/workspace` which looks like it is a leftover from the developer machine.

```
Generating: '/home/me/gr-opssat/apps/os_uhf_rx.py'

Executing: /usr/bin/python -u /home/me/gr-opssat/apps/os_uhf_rx.py

/home/osops/tom/dev/workspace/osat_437.16M_200k_beacon_mode6.cf32: No such file or directory
Traceback (most recent call last):
  File "/home/me/gr-opssat/apps/os_uhf_rx.py", line 252, in <module>
    main()
  File "/home/me/gr-opssat/apps/os_uhf_rx.py", line 240, in main
    tb = top_block_cls()
  File "/home/me/gr-opssat/apps/os_uhf_rx.py", line 146, in __init__
    self.blocks_file_source_0 = blocks.file_source(gr.sizeof_gr_complex*1, '/home/osops/tom/dev/workspace/osat_437.16M_200k_beacon_mode6.cf32', True)
  File "/usr/lib/python2.7/dist-packages/gnuradio/blocks/blocks_swig0.py", line 1092, in make
    return _blocks_swig0.file_source_make(itemsize, filename, repeat)
RuntimeError: can't open file
```

To reproduce:
* Run Ubuntu Bionic
* `apt-get -y install gnuradio python-construct`
* Compile and install https://github.com/wnagele/gr-gpredict-doppler
* Compile and install https://github.com/daniestevez/libfec/
* Compile and install https://github.com/daniestevez/gr-satellites
* In GNU Radio Companion, load `os_uhf_rc.grc` and click the "run" button

**Comment by mathzol** [comment]
This is not a real issue, I think, you have to rebrowse the osat_437.16M_200k_beacon_mode6.cf32 file after you extract it. You can find it in folder named: recordings.

**Comment by TomMladenov** [comment]
Indeed, as @mathzol points out, and also described in the readme, that the recording should be unzipped and the path in the file source adjusted to point to the recording.

**Comment by probonopd** [comment]
Thank you very much.
