### ISSUE TITLE
os_demod_decode.py: unsupported operand type(s) for *

### ISSUE THREAD

**Issue by probonopd** [esa/gr-opssat#4]
```
Generating: '/home/me/gr-opssat/apps/os_demod_decode.py'
>>> Warning: This flow graph may not have flow control: no audio or RF hardware blocks found. Add a Misc->Throttle block to your flow graph to avoid CPU congestion.

Executing: /usr/bin/python -u /home/me/gr-opssat/apps/os_demod_decode.py

Traceback (most recent call last):
  File "/home/me/gr-opssat/apps/os_demod_decode.py", line 37, in <module>
    import satellites
  File "/usr/lib/python2.7/dist-packages/satellites/__init__.py", line 103, in <module>
    from sat_3cat_1_telemetry_parser import sat_3cat_1_telemetry_parser
  File "/usr/lib/python2.7/dist-packages/satellites/sat_3cat_1_telemetry_parser.py", line 26, in <module>
    import sat_3cat_1_telemetry
  File "/usr/lib/python2.7/dist-packages/satellites/sat_3cat_1_telemetry.py", line 109, in <module>
    'beacon_id' / BeaconID * set_delta_min_delay,\
TypeError: unsupported operand type(s) for *: 'Renamed' and 'function'

>>> Done
```

To reproduce:
* Run Ubuntu Bionic
* `apt-get -y install gnuradio python-construct`
* Compile and install https://github.com/wnagele/gr-gpredict-doppler
* Compile and install https://github.com/daniestevez/libfec/
* Compile and install https://github.com/daniestevez/gr-satellites
* In GNU Radio Companion, load `os_demod_decode.grc` and click the "run" button

**Comment by mathzol** [comment]
You have to install the right version of python-construct. 2.9 You got I think now the 2.8.

**Comment by TomMladenov** [comment]
Exactly, please refer to the complete gr-satellites dependency documentation.

**Comment by probonopd** [comment]
Thank you very much. This probably means that I cannot use the `python-construct` from the Linux distribution but should use the one from pip instead.

**Comment by mathzol** [comment]
If you want to use the pip version  rather, you have to remove the apt version first than install the pip 2.9 version. If both are installed the system will prefer the apt version, which is the older one 2.8.
